name: Update stats

on:
  schedule:
    - cron: "0 5 * * *" # every 24 hours
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          # token: ${{ secrets.USER_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Status
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name 'Nedd Chairi Muñoz'
          git config user.email 'neddchairiweb@gmail.com'
          git add .
          git commit -m "Update README.md"
          git push
          fi
